package: yrewrite_metainfo
version: "3.0.0"
author: "Alexander Walther"
supportpage: https://github.com/alexplusde/yrewrite_metainfo/

requires:
    php:
        version: ">7.3"
    redaxo: ^5.12
    packages:
        yform: ">=4"
        metainfo: ">1"

page:
    title: translate:yrewrite_metainfo
    icon: rex-icon fa-globe

pages:
    metainfo/yrewrite_fields:
        title: translate:yrewrite_metainfo_fields
        perm: yrewrite_metainfo['fields']
    yrewrite/metainfo:
        title: translate:yrewrite_metainfo_domain
        prio: 15
        icon: rex-icon fa-globe
        perm: yrewrite_metainfo['domain']
