package: yrewrite_metainfo
version: "2.0.0-dev-2024-08-09"
author: "Alexander Walther"
supportpage: https://github.com/alexplusde/yrewrite_metainfo/

requires:
    php:
        version: "^8.3"
    redaxo: ^5.17
    packages:
        yrewrite: "^2"
        yform: "^4"

pages:
    yrewrite/metainfo:
        title: translate:yrewrite_metainfo_title
        perm: yrewrite_metainfo['fields']
    yrewrite/metainfo/domain:
        title: translate:yrewrite_metainfo_domain
        perm: yrewrite_metainfo['domain']
    yrewrite/metainfo/domain_icon:
        title: translate:yrewrite_metainfo_domain_icon
        perm: yrewrite_metainfo['domain']
    yrewrite/metainfo/field:
        title: translate:yrewrite_metainfo_fields
        perm: yrewrite_metainfo['fields']
