package: yrewrite_metainfo
version: "0.0.1"
author: "Alexander Walther"
supportpage: https://github.com/alexplusde/yrewrite_metainfo/

requires:
    php:
        version: ">7.3"
    redaxo: ^5.12
    packages:
        yform: ">=4"
        metainfo: ">1"

pages:
    yrewrite/metainfo:
        title: translate:yrewrite_metainfo_title
        perm: yrewrite_metainfo['fields']
    yrewrite/metainfo/domain:
        title: translate:yrewrite_metainfo_domain
        prio: 15
        perm: yrewrite_metainfo['domain']
    yrewrite/metainfo/field:
        title: translate:yrewrite_metainfo_fields
        perm: yrewrite_metainfo['fields']
